Inspections/Inspection/Models/ErrorViewModel.cs
using System;

namespace Inspection.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Inspections/Inspection/Controllers/HomeController.cs
using Inspection.Models;
using Inspection.DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using Inspection.BLL;
using Microsoft.AspNetCore.Http;

namespace Inspection.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private PoliciesBLL _policiesBLL;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            
        }

        public IActionResult Index()
        {
            _policiesBLL = new PoliciesBLL();

            List<PoliciesVM> PoliciesList = _policiesBLL.GetPoliciesInbox(Convert.ToDateTime("2021-12-01"), DateTime.Now);

            return View(PoliciesList);
        }


        public ActionResult Create(string PolicyNumber)
        {
            
            return RedirectToAction("Index");
        }

        // POST: Home/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Inspections/Inspection/Controllers/InspectionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Inspection.BLL;

namespace Inspection.Controllers
{
    public class InspectionController : Controller
    {
        // GET: InspectionController
        public ActionResult Index()
        {
            InspectionBLL _obj = new InspectionBLL();
            return View(_obj);
        }

        // GET: InspectionController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: InspectionController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InspectionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: InspectionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: InspectionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //// GET: InspectionController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: InspectionController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Inspections/Inspection/Views/Home/Index.cshtml
@model IEnumerable<Inspection.DAL.Models.PoliciesVM>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Inbox</h1>
@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PolicyNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuoteNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Coverage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Carrier)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BindDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EffectiveDateFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PolicyStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaymentMethod)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PolicyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuoteNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Coverage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Carrier)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BindDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EffectiveDateFrom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PolicyStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentMethod)
            </td>
            <td>
                @*<button class="btn btn-success"> </button>*@
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                @Html.ActionLink("Assign it to me", "Create", new { id = item.PolicyNumber }, new { onclick = "return confirm('Are sure wants to Assign it to yourself?');" })
                @*<input type="button" value="Go Somewhere Else" onclick="location.href='<%: Url.Action(Create,InspectionController , new { parameter1=value1 }) %>'" />*@
            </td>
        </tr>
}
    </tbody>
</table>

Inspections/Inspection/Views/Inspection/Edit.cshtml
@model Inspection.DAL.ViewModels.InspectionVM

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>InspectionVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PolicyNumber" class="control-label"></label>
                <input asp-for="PolicyNumber" class="form-control" />
                <span asp-validation-for="PolicyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="User" class="control-label"></label>
                <input asp-for="User" class="form-control" />
                <span asp-validation-for="User" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Notes" class="control-label"></label>
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Inspections/Inspection/Views/Inspection/Index.cshtml
@model IEnumerable<Inspection.DAL.ViewModels.InspectionVM>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PolicyNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PolicyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Inspections/Inspection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inspection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inspection</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inspection" asp-action="Index">Inspections</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Inspection - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>